controls:
  - commands:
    - G91
    - G28 X Y
    - G90
    - G0 Y0 F10800
    name: Move to Purge
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
printerProfiles:
  default: saam
plugins:
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart
serial:
  longRunningCommands:
  - G4
  - G28
  - G29
  - G30
  - G32
  - M400
  - M226
  - M600
  - G27
  - M68
  autoUppercaseBlacklist:
  - M117
  - M38