#!/usr/bin/env bash
# OctoPI generation script
# Helper script that runs in a Raspbian chroot to create the OctoPI distro
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
set -x
set -e

export LC_ALL=C

source /common.sh

function gitoauthclone(){
    repo_build_var=$1_URL
    repo_branch_var=$1_BRANCH
    repo_token_var=$1_OAUTHTOKEN

    repo_dir=$2

    build_repo=${!repo_build_var}
    ship_repo=${!repo_build_var}
    branch=${!repo_branch_var}
    authtoken=${!repo_token_var}

    if [ -n "$authtoken" ]
    then
        build_repo=$(echo $build_repo | sed "s/https:\/\//https:\/\/${authtoken}\@/")
    fi

    sudo -u pi mkdir -p "$repo_dir"
    pushd "$repo_dir"
        sudo -u pi git init
        sudo -u pi git pull "$build_repo" "$branch"
        sudo -u pi git remote add origin "$ship_repo"
    popd
}

sudo -u pi mkdir -p /home/pi/.octoprint/plugins

pushd /home/pi/.octoprint/plugins
    echo "--- Installing Removal Plugin"
    gitoauthclone REMOVAL_REPO removal
popd